FROM nginx:1.27.5-alpine

WORKDIR /app 

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf

COPY index.html /usr/share/nginx/html/index.html
COPY assets/ /usr/share/nginx/html/assets/
COPY js/ /usr/share/nginx/html/js/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
#healthcheck
#dockerignore   
#mutli-stage build