# Imagen base para .NET
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app

# Copiar los archivos del proyecto
COPY . /app/

# Restaurar dependencias y construir el proyecto
RUN dotnet restore
RUN dotnet publish -c Release -o out

# Imagen para ejecución
FROM mcr.microsoft.com/dotnet/aspnet:7.0
WORKDIR /app
COPY --from=build /app/out ./

# Exponer el puerto 80
EXPOSE 80

# Comando de inicio
ENTRYPOINT ["dotnet", "Worker.dll"]
