version: '3.8'

services:
  control-db-dotnet:
    build:
      context: ./worker
      dockerfile: Dockerfile
    image: control-db-dotnet:v1
    ports:
      - "5000:80"
    networks:
      - votacion-red
    depends_on:
      - db
      - redis

  back-python:
    build:
      context: ./vote
      dockerfile: Dockerfile
    image: back-python:v1
    ports:
      - "5001:80"
    networks:
      - votacion-red
    depends_on:
      - redis

  front-node:
    build:
      context: ./result
      dockerfile: dockerfile
    image: front-node:v1
    ports:
      - "5002:4000"
    networks:
      - votacion-red
    depends_on:
      - db
      - redis

  db:
    build:
      context: ./db
      dockerfile: dockerfile
    image: postgres:v1
    environment:
      POSTGRES_PASSWORD: postgres
    networks:
      - votacion-red

  redis:
    build:
      context: ./redis
      dockerfile: dockerfile
    image: redis:v1
    networks:
      - votacion-red

networks:
  votacion-red:
    driver: bridge
